# Generated by Django 4.1.4 on 2022-12-17 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broken', models.BooleanField(default=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bank',
                'ordering': ['added'],
            },
        ),
        migrations.CreateModel(
            name='BankContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('coin', 'Coin'), ('bank_note', 'Bank Note')], max_length=9)),
                ('amount', models.PositiveIntegerField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='bank.bank')),
            ],
            options={
                'db_table': 'content',
                'ordering': ['added'],
            },
        ),
    ]
